"use client";
import {useEffect,useRef,useState} from "react";
import {Clapperboard,Copy,CheckCircle2,CalendarClock,Rocket,Image as ImageIcon,Upload,Film,X,Trash2,RefreshCw} from "lucide-react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
type Product={id:number;title:string;image_url:string;marketplace:string;price:number;affiliate_url:string};
type Variant={id:number;platform:string;title:string;hook:string;caption:string;script:string;hashtags:string;cta:string;media_url:string;media_filename:string;media_content_type:string;media_size:number;media_duration_seconds:number;has_uploaded_media:boolean;affiliate_url:string;affiliate_label:string;link_placement:string;affiliate_configured:boolean;affiliate_configured_at?:string;status:string};
type Pub={id:number;platform:string;status:string;scheduled_at?:string;published_at?:string;external_post_id?:string;error_message?:string;tiktok_status?:string;tiktok_fail_reason?:string;uploaded_bytes?:number;public_post_ids?:string};
type Campaign={id:number;product_id:number;name:string;objective:string;format:string;duration_seconds:number;tone:string;audience:string;status:string;variants:Variant[];publications:Pub[]};
type CreatorInfo={creator_username?:string;creator_nickname?:string;creator_avatar_url?:string;privacy_level_options:string[];comment_disabled:boolean;duet_disabled:boolean;stitch_disabled:boolean;max_video_post_duration_sec?:number};
const privacyLabel:Record<string,string>={PUBLIC_TO_EVERYONE:"Público",MUTUAL_FOLLOW_FRIENDS:"Amigos mútuos",FOLLOWER_OF_CREATOR:"Seguidores",SELF_ONLY:"Somente eu"};
function sizeLabel(n:number){if(!n)return "";if(n<1024*1024)return `${(n/1024).toFixed(0)} KB`;return `${(n/1024/1024).toFixed(1)} MB`}
export default function Content(){
 const [key,setKey]=useState(""),[products,setProducts]=useState<Product[]>([]),[product,setProduct]=useState(""),[platforms,setPlatforms]=useState<string[]>(["TikTok"]),[duration,setDuration]=useState(30),[objective,setObjective]=useState("Venda"),[format,setFormat]=useState("Vídeo curto"),[tone,setTone]=useState("Direto e acessível"),[audience,setAudience]=useState(""),[active,setActive]=useState<Campaign|null>(null),[history,setHistory]=useState<any[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[scheduleAt,setScheduleAt]=useState("");
 const [mediaVariant,setMediaVariant]=useState<Variant|null>(null),[mediaFile,setMediaFile]=useState<File|null>(null),[mediaDuration,setMediaDuration]=useState(0),[uploading,setUploading]=useState(false),[dragging,setDragging]=useState(false);
 const [publishOpen,setPublishOpen]=useState(false),[creator,setCreator]=useState<CreatorInfo|null>(null),[privacy,setPrivacy]=useState("SELF_ONLY"),[disableComment,setDisableComment]=useState(false),[disableDuet,setDisableDuet]=useState(false),[disableStitch,setDisableStitch]=useState(false),[consent,setConsent]=useState(false),[brandContent,setBrandContent]=useState(true),[brandOrganic,setBrandOrganic]=useState(false),[isAigc,setIsAigc]=useState(false),[creatorBusy,setCreatorBusy]=useState(false);
 const [linkDrafts,setLinkDrafts]=useState<Record<number,{url:string;label:string;placement:string}>>({});
 const [linkSaving,setLinkSaving]=useState<Record<number,boolean>>({});
 const [linkFeedback,setLinkFeedback]=useState<Record<number,{kind:"ok"|"error"|"dirty";text:string}>>({});
 const fileRef=useRef<HTMLInputElement>(null);
 async function req(path:string,method="GET",body?:any){const r=await fetch(`${API}/api/v1/social${path}`,{method,headers:{"Content-Type":"application/json","X-Admin-Key":key},body:body?JSON.stringify(body):undefined,cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||JSON.stringify(d));return d}
 async function loadProducts(){try{const d=await req("/products");setProducts(d);if(!product&&d[0])setProduct(String(d[0].id));setMessage("")}catch(e){setMessage(String(e))}}
 async function loadHistory(){try{setHistory(await req("/campaigns"))}catch(e){setMessage(String(e))}}
 async function create(){setBusy(true);try{const d=await req("/campaigns","POST",{product_id:Number(product),platforms,objective,format,duration_seconds:duration,tone,audience});setActive(d);setMessage("Campanha criada. Revise as versões, adicione a mídia e aprove antes de publicar.");await loadHistory()}catch(e){setMessage(String(e))}finally{setBusy(false)}}
 async function detail(id:number){try{const d=await req(`/campaigns/${id}`);setActive(d);const drafts:Record<number,{url:string;label:string;placement:string}>={};for(const v of d.variants||[])drafts[v.id]={url:v.affiliate_url||"",label:v.affiliate_label||"",placement:v.link_placement||"bio"};setLinkDrafts(drafts)}catch(e){setMessage(String(e))}}
 async function approve(){if(!active)return;try{await req(`/campaigns/${active.id}/approve`,"POST",{approved:true});await detail(active.id);setMessage("Campanha aprovada para publicação.")}catch(e){setMessage(String(e))}}
 function openMedia(v:Variant){setMediaVariant(v);setMediaFile(null);setMediaDuration(0);setDragging(false)}
 async function uploadMedia(){if(!mediaVariant||!mediaFile)return;setUploading(true);try{const fd=new FormData();fd.append("file",mediaFile);fd.append("duration_seconds",String(Math.round(mediaDuration||0)));const r=await fetch(`${API}/api/v1/social/variants/${mediaVariant.id}/media/upload`,{method:"POST",headers:{"X-Admin-Key":key},body:fd});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||JSON.stringify(d));setMediaVariant(null);setMediaFile(null);if(active)await detail(active.id);setMessage("Vídeo armazenado e vinculado à campanha.")}catch(e){setMessage(String(e))}finally{setUploading(false)}}
 async function saveAffiliate(v:Variant){const d=linkDrafts[v.id]||{url:v.affiliate_url||"",label:v.affiliate_label||"",placement:v.link_placement||"bio"};setLinkSaving(x=>({...x,[v.id]:true}));setLinkFeedback(x=>({...x,[v.id]:{kind:"dirty",text:"Salvando..."}}));try{const saved=await req(`/variants/${v.id}/affiliate-link`,"PUT",{affiliate_url:d.url.trim(),affiliate_label:d.label.trim(),link_placement:d.placement});setLinkDrafts(x=>({...x,[v.id]:{url:saved.affiliate_url||"",label:saved.affiliate_label||"",placement:saved.link_placement||"bio"}}));setLinkFeedback(x=>({...x,[v.id]:{kind:"ok",text:"✓ Configuração salva no banco."}}));if(active){const fresh=await req(`/campaigns/${active.id}`);setActive(fresh)}setMessage("Link/etiqueta da campanha salvo com sucesso.")}catch(e){const msg=String(e);setLinkFeedback(x=>({...x,[v.id]:{kind:"error",text:`⚠ ${msg}`}}));setMessage(msg)}finally{setLinkSaving(x=>({...x,[v.id]:false}))}}
 function draft(v:Variant,patch:any){setLinkDrafts(x=>({...x,[v.id]:{url:x[v.id]?.url??v.affiliate_url??"",label:x[v.id]?.label??v.affiliate_label??"",placement:x[v.id]?.placement??v.link_placement??"bio",...patch}}));setLinkFeedback(x=>({...x,[v.id]:{kind:"dirty",text:"● Alterações não salvas"}}))}
 async function removeMedia(v:Variant){if(!confirm("Remover esta mídia da campanha?"))return;try{await req(`/variants/${v.id}/media`,"DELETE");if(active)await detail(active.id);setMessage("Mídia removida.")}catch(e){setMessage(String(e))}}
 async function openPublish(){if(!active)return;const hasTikTok=active.variants.some(v=>v.platform==="TikTok");if(!hasTikTok){await queue({});return}setCreatorBusy(true);setPublishOpen(true);setConsent(false);setBrandContent(true);setBrandOrganic(false);setIsAigc(false);try{const info=await req("/tiktok/creator-info");setCreator(info);const opts=info.privacy_level_options||[];setPrivacy(opts.includes("SELF_ONLY")?"SELF_ONLY":opts[0]||"");setDisableComment(!!info.comment_disabled);setDisableDuet(!!info.duet_disabled);setDisableStitch(!!info.stitch_disabled)}catch(e){setMessage(String(e));setPublishOpen(false)}finally{setCreatorBusy(false)}}
 async function queue(tiktok:any){if(!active)return;try{const body={scheduled_at:scheduleAt?new Date(scheduleAt).toISOString():null,...tiktok};await req(`/campaigns/${active.id}/schedule`,"POST",body);setPublishOpen(false);await detail(active.id);setMessage(scheduleAt?"Publicações agendadas.":"Publicações colocadas na fila.")}catch(e){setMessage(String(e))}}
 async function confirmPublish(){await queue({tiktok_privacy_level:privacy,tiktok_disable_comment:disableComment,tiktok_disable_duet:disableDuet,tiktok_disable_stitch:disableStitch,tiktok_user_consent:consent,tiktok_brand_content:brandContent,tiktok_brand_organic:brandOrganic,tiktok_is_aigc:isAigc})}
 async function run(id:number){try{const d=await req(`/publications/${id}/run`,"POST",{});if(active)await detail(active.id);setMessage(d.status==="processing"?"Vídeo enviado ao TikTok e em processamento.":d.error_message||`Status: ${d.status}`)}catch(e){setMessage(String(e))}}
 async function refreshStatus(id:number){try{const d=await req(`/publications/${id}/status`,"POST",{});if(active)await detail(active.id);setMessage(d.status==="published"?"Publicação concluída no TikTok.":d.status==="error"?d.error_message:"TikTok ainda está processando o vídeo.")}catch(e){setMessage(String(e))}}
 function toggle(p:string){setPlatforms(x=>x.includes(p)?x.filter(y=>y!==p):[...x,p])}
 useEffect(()=>{const p=new URLSearchParams(location.search).get("product");if(p)setProduct(p)},[]);
 const chosen=products.find(p=>p.id===Number(product));
 return <><div className="page-header"><div><span className="eyebrow">ESTÚDIO / CAMPANHAS</span><h1 className="page-title">Social Publishing</h1><p className="muted">Produto → conteúdo → mídia → aprovação → publicação.</p></div><span className="pill"><Rocket size={14}/> V1.8.1</span></div>
 <div className="split"><section className="card"><h2 className="section-title"><Clapperboard size={19}/> Criar campanha</h2><div className="field"><label>Chave administrativa</label><input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="ADMIN_SETUP_KEY"/></div><div className="row-actions" style={{marginTop:10}}><button className="btn ghost" disabled={!key} onClick={()=>{loadProducts();loadHistory()}}>Carregar catálogo</button></div>
 <div className="field" style={{marginTop:16}}><label>Produto afiliado</label><select value={product} onChange={e=>setProduct(e.target.value)}><option value="">Selecione...</option>{products.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></div>{chosen&&<div className="selected-product">{chosen.image_url?<img src={chosen.image_url} alt=""/>:<span className="placeholder"><ImageIcon/></span>}<div><b>{chosen.title}</b><small>{chosen.marketplace} · {chosen.price?`R$ ${chosen.price.toFixed(2)}`:"Preço não confirmado"}</small><span className="status-ok">Link afiliado ✓</span></div></div>}
 <div className="field" style={{marginTop:16}}><label>Redes</label><div className="network-picks">{["Instagram","TikTok","YouTube Shorts","Pinterest"].map(p=><button type="button" key={p} className={platforms.includes(p)?"network active":"network"} onClick={()=>toggle(p)}>{p}</button>)}</div></div>
 <div className="campaign-grid"><div className="field"><label>Objetivo</label><select value={objective} onChange={e=>setObjective(e.target.value)}><option>Venda</option><option>Tráfego</option><option>Engajamento</option></select></div><div className="field"><label>Formato</label><select value={format} onChange={e=>setFormat(e.target.value)}><option>Vídeo curto</option><option>Imagem</option><option>Carrossel</option></select></div><div className="field"><label>Duração</label><select value={duration} onChange={e=>setDuration(Number(e.target.value))}><option value="15">15 s</option><option value="30">30 s</option><option value="60">60 s</option></select></div><div className="field"><label>Tom</label><select value={tone} onChange={e=>setTone(e.target.value)}><option>Direto e acessível</option><option>Informativo</option><option>Entusiasmado</option><option>Premium</option></select></div></div><div className="field" style={{marginTop:12}}><label>Público-alvo (opcional)</label><input value={audience} onChange={e=>setAudience(e.target.value)} placeholder="Ex.: pessoas buscando cuidados com a pele"/></div><button className="btn primary" style={{marginTop:18}} disabled={!key||!product||!platforms.length||busy} onClick={create}>✨ Criar campanha</button></section>
 <section className="card"><h2 className="section-title">Campanhas</h2>{history.length?history.map(c=><button key={c.id} className="btn ghost history-btn" onClick={()=>detail(c.id)}>#{c.id} · {c.name}<small>{c.status} · {c.duration_seconds}s</small></button>):<p className="muted">Carregue o catálogo para consultar o histórico.</p>}</section></div>
 {message&&<div className="alert">{message}</div>}
 {active&&<section className="card" style={{marginTop:20}}><div className="page-header"><div><span className="eyebrow">CAMPANHA #{active.id}</span><h2>{active.name}</h2><p className="muted">{active.objective} · {active.format} · {active.duration_seconds}s · {active.tone}</p></div><span className="badge dim">{active.status}</span></div>
 <div className="variant-grid">{active.variants.map(v=><article className="variant" key={v.id}><div className="variant-head"><b>{v.platform}</b><span className="badge dim">{v.status}</span></div><h4>Gancho</h4><div className="content-box">{v.hook}</div><h4>Roteiro</h4><div className="content-box">{v.script}</div><h4>Legenda</h4><div className="content-box">{v.caption}</div><div className="affiliate-box"><h4>Link de afiliado / etiqueta</h4><div className="campaign-grid"><div className="field"><label>Link oficial</label><input value={linkDrafts[v.id]?.url??v.affiliate_url??""} onChange={e=>draft(v,{url:e.target.value})}/></div><div className="field"><label>Etiqueta ML</label><input value={linkDrafts[v.id]?.label??v.affiliate_label??""} onChange={e=>draft(v,{label:e.target.value})} placeholder="ex.: tiktokps0301"/></div><div className="field"><label>Uso do link</label><select value={linkDrafts[v.id]?.placement??v.link_placement??"bio"} onChange={e=>draft(v,{placement:e.target.value})}><option value="bio">Link na bio/perfil</option><option value="caption">Legenda/descrição</option><option value="manual">Manual</option></select></div></div><div className="row-actions" style={{marginTop:10}}><button className="btn ghost" disabled={!!linkSaving[v.id]} onClick={()=>saveAffiliate(v)}>{linkSaving[v.id]?"Salvando...":"Salvar link"}</button>{v.affiliate_configured&&!linkFeedback[v.id]&&<span className="status-ok">✓ Configuração salva</span>}{linkFeedback[v.id]&&<span className={linkFeedback[v.id].kind==="error"?"error-text":linkFeedback[v.id].kind==="ok"?"status-ok":"mini"}>{linkFeedback[v.id].text}</span>}</div>{v.platform==="TikTok"&&<p className="mini">No TikTok o CTA não depende de URL clicável na legenda. Use o link oficial no perfil quando disponível e a etiqueta do Mercado Livre para atribuição.</p>}</div>{v.has_uploaded_media&&<div className="media-chip"><Film size={18}/><div><b>{v.media_filename}</b><small>{sizeLabel(v.media_size)} · {v.media_content_type}</small></div><button title="Remover mídia" onClick={()=>removeMedia(v)}><Trash2 size={15}/></button></div>}<div className="row-actions" style={{marginTop:12}}><button className="btn ghost" onClick={()=>navigator.clipboard.writeText(v.caption)}><Copy size={14}/> Copiar</button><button className="btn ghost" onClick={()=>openMedia(v)}><Upload size={14}/> {v.has_uploaded_media?"Trocar vídeo":"Adicionar vídeo"}</button></div></article>)}</div>
 <div className="publish-bar"><div><b>Revisão e publicação</b><p className="mini">A publicação só entra na fila depois da aprovação humana.</p></div><div className="row-actions"><button className="btn ghost" disabled={active.status==="approved"} onClick={approve}><CheckCircle2 size={15}/> Aprovar</button><input className="input schedule-input" type="datetime-local" value={scheduleAt} onChange={e=>setScheduleAt(e.target.value)}/><button className="btn primary" disabled={active.status!=="approved"} onClick={openPublish}><CalendarClock size={15}/> {scheduleAt?"Agendar":"Colocar na fila"}</button></div></div>
 {active.publications.length>0&&<div className="table-wrap" style={{marginTop:18}}><table className="table"><thead><tr><th>Rede</th><th>Status</th><th>Agendado</th><th>Resultado</th><th>Ação</th></tr></thead><tbody>{active.publications.map(p=><tr key={p.id}><td>{p.platform}</td><td><span className="badge dim">{p.status}</span></td><td>{p.scheduled_at?new Date(p.scheduled_at).toLocaleString("pt-BR"):"Agora"}</td><td>{p.error_message?<span className="error-text">{p.error_message}</span>:<div><b>{p.tiktok_status||p.status}</b>{p.external_post_id&&<small style={{display:"block"}}>{p.external_post_id}</small>}{!!p.uploaded_bytes&&<small style={{display:"block"}}>Transferido: {sizeLabel(p.uploaded_bytes)}</small>}{p.public_post_ids&&<small style={{display:"block"}}>Post ID: {p.public_post_ids}</small>}</div>}</td><td><div className="row-actions"><button className="btn ghost" disabled={!['queued','scheduled','error'].includes(p.status)} onClick={()=>run(p.id)}>Publicar/testar</button>{p.platform==="TikTok"&&p.external_post_id&&<button className="btn ghost" onClick={()=>refreshStatus(p.id)}><RefreshCw size={14}/> Status</button>}</div></td></tr>)}</tbody></table></div>}</section>}
 {mediaVariant&&<div className="modal-backdrop" onMouseDown={()=>!uploading&&setMediaVariant(null)}><div className="modal-card" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">MÍDIA DA CAMPANHA</span><h3>Adicionar vídeo</h3></div><button className="icon-btn" onClick={()=>setMediaVariant(null)}><X/></button></div><div className={`dropzone ${dragging?"dragging":""}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);setMediaFile(e.dataTransfer.files?.[0]||null)}} onClick={()=>fileRef.current?.click()}><input ref={fileRef} hidden type="file" accept="video/mp4,video/quicktime,video/webm" onChange={e=>setMediaFile(e.target.files?.[0]||null)}/><Upload size={34}/>{mediaFile?<><b>{mediaFile.name}</b><span>{sizeLabel(mediaFile.size)} · {mediaFile.type||"vídeo"}</span></>:<><b>Arraste o vídeo aqui</b><span>ou clique para selecionar · MP4, MOV ou WebM</span></>}</div>{mediaFile&&<><video className="video-preview" controls src={URL.createObjectURL(mediaFile)} onLoadedMetadata={e=>setMediaDuration((e.currentTarget as HTMLVideoElement).duration||0)}/><p className="mini">Duração detectada: {mediaDuration?`${Math.round(mediaDuration)}s`:"lendo..."}. A campanha será sincronizada com a mídia.</p></>}<div className="modal-actions"><button className="btn ghost" disabled={uploading} onClick={()=>setMediaVariant(null)}>Cancelar</button><button className="btn primary" disabled={!mediaFile||uploading} onClick={uploadMedia}>{uploading?"Enviando...":"Adicionar vídeo"}</button></div></div></div>}
 {publishOpen&&<div className="modal-backdrop"><div className="modal-card publish-modal"><div className="modal-head"><div><span className="eyebrow">TIKTOK DIRECT POST</span><h3>Configurar publicação</h3></div><button className="icon-btn" onClick={()=>setPublishOpen(false)}><X/></button></div>{creatorBusy?<p className="muted">Consultando configurações atuais da conta TikTok...</p>:creator&&<><div className="creator-box">{creator.creator_avatar_url&&<img src={creator.creator_avatar_url} alt=""/>}<div><b>{creator.creator_nickname||"Conta TikTok"}</b><small>@{creator.creator_username||"tiktok"}</small></div></div><div className="field"><label>Quem pode assistir</label><select value={privacy} onChange={e=>setPrivacy(e.target.value)}>{(creator.privacy_level_options||[]).map(x=><option key={x} value={x}>{privacyLabel[x]||x}</option>)}</select></div><div className="toggle-list"><label><input type="checkbox" checked={disableComment} disabled={creator.comment_disabled} onChange={e=>setDisableComment(e.target.checked)}/> Desativar comentários</label><label><input type="checkbox" checked={disableDuet} disabled={creator.duet_disabled} onChange={e=>setDisableDuet(e.target.checked)}/> Desativar Dueto</label><label><input type="checkbox" checked={disableStitch} disabled={creator.stitch_disabled} onChange={e=>setDisableStitch(e.target.checked)}/> Desativar Stitch</label></div><div className="field"><label>Divulgação de conteúdo comercial</label><div className="toggle-list"><label><input type="checkbox" checked={brandContent} onChange={e=>setBrandContent(e.target.checked)}/> Conteúdo de terceiro / parceria comercial</label><label><input type="checkbox" checked={brandOrganic} onChange={e=>setBrandOrganic(e.target.checked)}/> Promove minha própria marca</label><label><input type="checkbox" checked={isAigc} onChange={e=>setIsAigc(e.target.checked)}/> Conteúdo gerado por IA (AIGC)</label></div>{brandContent&&privacy==="SELF_ONLY"&&<p className="error-text">Atenção: o TikTok não permite Branded Content com visibilidade Somente eu. Em cliente ainda não auditado, use esta tela para revisão/auditoria e não force uma publicação incompatível.</p>}</div><label className="consent-box"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Confirmo que revisei o conteúdo e autorizo o Affiliate Intelligence a enviar este vídeo para minha conta TikTok.</span></label><p className="mini">As opções acima foram consultadas diretamente na conta TikTok antes do envio.</p><div className="modal-actions"><button className="btn ghost" onClick={()=>setPublishOpen(false)}>Cancelar</button><button className="btn primary" disabled={!consent||!privacy||(brandContent&&privacy==="SELF_ONLY")} onClick={confirmPublish}>{scheduleAt?"Confirmar agendamento":"Confirmar e colocar na fila"}</button></div></>}</div></div>}
 </>}
