"use client";
import {useEffect,useState} from "react";
import {Clapperboard,Copy,CheckCircle2,CalendarClock,Rocket,Image as ImageIcon} from "lucide-react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
type Product={id:number;title:string;image_url:string;marketplace:string;price:number;affiliate_url:string};
type Variant={id:number;platform:string;title:string;hook:string;caption:string;script:string;hashtags:string;cta:string;media_url:string;status:string};
type Pub={id:number;platform:string;status:string;scheduled_at?:string;published_at?:string;external_post_id?:string;error_message?:string};
type Campaign={id:number;product_id:number;name:string;objective:string;format:string;duration_seconds:number;tone:string;audience:string;status:string;variants:Variant[];publications:Pub[]};
export default function Content(){
 const [key,setKey]=useState(""),[products,setProducts]=useState<Product[]>([]),[product,setProduct]=useState(""),[platforms,setPlatforms]=useState<string[]>(["TikTok"]),[duration,setDuration]=useState(30),[objective,setObjective]=useState("Venda"),[format,setFormat]=useState("Vídeo curto"),[tone,setTone]=useState("Direto e acessível"),[audience,setAudience]=useState(""),[active,setActive]=useState<Campaign|null>(null),[history,setHistory]=useState<any[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[scheduleAt,setScheduleAt]=useState("");
 async function req(path:string,method="GET",body?:any){const r=await fetch(`${API}/api/v1/social${path}`,{method,headers:{"Content-Type":"application/json","X-Admin-Key":key},body:body?JSON.stringify(body):undefined,cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.detail||JSON.stringify(d));return d}
 async function loadProducts(){try{const d=await req("/products");setProducts(d);if(!product&&d[0])setProduct(String(d[0].id))}catch(e){setMessage(String(e))}}
 async function loadHistory(){try{setHistory(await req("/campaigns"))}catch(e){setMessage(String(e))}}
 async function create(){setBusy(true);try{const d=await req("/campaigns","POST",{product_id:Number(product),platforms,objective,format,duration_seconds:duration,tone,audience});setActive(d);setMessage("Campanha criada. Revise as versões e aprove antes de publicar.");await loadHistory()}catch(e){setMessage(String(e))}finally{setBusy(false)}}
 async function detail(id:number){try{setActive(await req(`/campaigns/${id}`))}catch(e){setMessage(String(e))}}
 async function approve(){if(!active)return;await req(`/campaigns/${active.id}/approve`,"POST",{approved:true});await detail(active.id);setMessage("Campanha aprovada para publicação.")}
 async function media(v:Variant){const u=prompt("URL HTTPS pública do vídeo/imagem para esta rede:",v.media_url||"");if(u===null)return;try{await req(`/variants/${v.id}/media`,"POST",{media_url:u});if(active)await detail(active.id)}catch(e){setMessage(String(e))}}
 async function queue(){if(!active)return;try{const body={scheduled_at:scheduleAt?new Date(scheduleAt).toISOString():null};await req(`/campaigns/${active.id}/schedule`,"POST",body);await detail(active.id);setMessage(scheduleAt?"Publicações agendadas.":"Publicações colocadas na fila.")}catch(e){setMessage(String(e))}}
 async function run(id:number){try{const d=await req(`/publications/${id}/run`,"POST",{});if(active)await detail(active.id);setMessage(d.status==="published"?"Enviado à plataforma.":d.error_message||"Falha ao publicar") }catch(e){setMessage(String(e))}}
 function toggle(p:string){setPlatforms(x=>x.includes(p)?x.filter(y=>y!==p):[...x,p])}
 useEffect(()=>{const p=new URLSearchParams(location.search).get("product");if(p)setProduct(p)},[]);
 const chosen=products.find(p=>p.id===Number(product));
 return <><div className="page-header"><div><span className="eyebrow">ESTÚDIO / CAMPANHAS</span><h1 className="page-title">Social Publishing</h1><p className="muted">Produto → campanha multicanal → aprovação → agendamento → publicação.</p></div><span className="pill"><Rocket size={14}/> V1.5</span></div>
 <div className="split"><section className="card"><h2 className="section-title"><Clapperboard size={19}/> Criar campanha</h2><div className="field"><label>Chave administrativa</label><input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="ADMIN_SETUP_KEY"/></div><div className="row-actions" style={{marginTop:10}}><button className="btn ghost" disabled={!key} onClick={()=>{loadProducts();loadHistory()}}>Carregar catálogo</button></div>
 <div className="field" style={{marginTop:16}}><label>Produto afiliado</label><select value={product} onChange={e=>setProduct(e.target.value)}><option value="">Selecione...</option>{products.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></div>{chosen&&<div className="selected-product">{chosen.image_url?<img src={chosen.image_url} alt=""/>:<span className="placeholder"><ImageIcon/></span>}<div><b>{chosen.title}</b><small>{chosen.marketplace} · {chosen.price?`R$ ${chosen.price.toFixed(2)}`:"Preço não confirmado"}</small><span className="status-ok">Link afiliado ✓</span></div></div>}
 <div className="field" style={{marginTop:16}}><label>Redes</label><div className="network-picks">{["Instagram","TikTok","YouTube Shorts","Pinterest"].map(p=><button type="button" key={p} className={platforms.includes(p)?"network active":"network"} onClick={()=>toggle(p)}>{p}</button>)}</div></div>
 <div className="campaign-grid"><div className="field"><label>Objetivo</label><select value={objective} onChange={e=>setObjective(e.target.value)}><option>Venda</option><option>Tráfego</option><option>Engajamento</option></select></div><div className="field"><label>Formato</label><select value={format} onChange={e=>setFormat(e.target.value)}><option>Vídeo curto</option><option>Imagem</option><option>Carrossel</option></select></div><div className="field"><label>Duração</label><select value={duration} onChange={e=>setDuration(Number(e.target.value))}><option value="15">15 s</option><option value="30">30 s</option><option value="60">60 s</option></select></div><div className="field"><label>Tom</label><select value={tone} onChange={e=>setTone(e.target.value)}><option>Direto e acessível</option><option>Informativo</option><option>Entusiasmado</option><option>Premium</option></select></div></div><div className="field" style={{marginTop:12}}><label>Público-alvo (opcional)</label><input value={audience} onChange={e=>setAudience(e.target.value)} placeholder="Ex.: pessoas buscando cuidados com a pele"/></div><button className="btn primary" style={{marginTop:18}} disabled={!key||!product||!platforms.length||busy} onClick={create}>✨ Criar campanha</button></section>
 <section className="card"><h2 className="section-title">Campanhas</h2>{history.length?history.map(c=><button key={c.id} className="btn ghost history-btn" onClick={()=>detail(c.id)}>#{c.id} · {c.name}<small>{c.status} · {c.duration_seconds}s</small></button>):<p className="muted">Carregue o catálogo para consultar o histórico.</p>}</section></div>
 {message&&<div className="alert">{message}</div>}
 {active&&<section className="card" style={{marginTop:20}}><div className="page-header"><div><span className="eyebrow">CAMPANHA #{active.id}</span><h2>{active.name}</h2><p className="muted">{active.objective} · {active.format} · {active.duration_seconds}s · {active.tone}</p></div><span className="badge dim">{active.status}</span></div>
 <div className="variant-grid">{active.variants.map(v=><article className="variant" key={v.id}><div className="variant-head"><b>{v.platform}</b><span className="badge dim">{v.status}</span></div><h4>Gancho</h4><div className="content-box">{v.hook}</div><h4>Roteiro</h4><div className="content-box">{v.script}</div><h4>Legenda</h4><div className="content-box">{v.caption}</div><div className="row-actions" style={{marginTop:12}}><button className="btn ghost" onClick={()=>navigator.clipboard.writeText(v.caption)}><Copy size={14}/> Copiar</button><button className="btn ghost" onClick={()=>media(v)}><ImageIcon size={14}/> {v.media_url?"Alterar mídia":"Adicionar mídia"}</button></div>{v.media_url&&<p className="mini status-ok">Mídia vinculada ✓</p>}</article>)}</div>
 <div className="publish-bar"><div><b>Revisão e publicação</b><p className="mini">A publicação só entra na fila depois da aprovação humana.</p></div><div className="row-actions"><button className="btn ghost" disabled={active.status==="approved"} onClick={approve}><CheckCircle2 size={15}/> Aprovar</button><input className="input schedule-input" type="datetime-local" value={scheduleAt} onChange={e=>setScheduleAt(e.target.value)}/><button className="btn primary" disabled={active.status!=="approved"} onClick={queue}><CalendarClock size={15}/> {scheduleAt?"Agendar":"Colocar na fila"}</button></div></div>
 {active.publications.length>0&&<div className="table-wrap" style={{marginTop:18}}><table className="table"><thead><tr><th>Rede</th><th>Status</th><th>Agendado</th><th>Resultado</th><th>Ação</th></tr></thead><tbody>{active.publications.map(p=><tr key={p.id}><td>{p.platform}</td><td><span className="badge dim">{p.status}</span></td><td>{p.scheduled_at?new Date(p.scheduled_at).toLocaleString("pt-BR"):"Agora"}</td><td>{p.error_message?<span className="error-text">{p.error_message}</span>:p.external_post_id||"—"}</td><td><button className="btn ghost" disabled={!['queued','scheduled','error'].includes(p.status)} onClick={()=>run(p.id)}>Publicar/testar</button></td></tr>)}</tbody></table></div>}</section>}</>}
