"use client";
import {useEffect,useState} from "react";
import {API,authToken} from "../../../lib/api";
import {saas} from "../../../lib/saas";
export default function Plano(){
 const[me,setMe]=useState<any>();const[plans,setPlans]=useState<any[]>([]);const[usage,setUsage]=useState<any>();const[billing,setBilling]=useState<any>();const[msg,setMsg]=useState('');
 const token=authToken;
 useEffect(()=>{saas('/me').then(setMe).catch(()=>{});saas('/plans').then(setPlans).catch(()=>{});saas('/usage').then(setUsage).catch(()=>{});fetch(`${API}/api/v1/billing/status`,{headers:{Authorization:`Bearer ${token()}`}}).then(r=>r.json()).then(setBilling).catch(()=>{})},[]);
 async function checkout(code:string){try{setMsg('Abrindo checkout seguro...');const r=await fetch(`${API}/api/v1/billing/checkout/${code}`,{method:'POST',headers:{Authorization:`Bearer ${token()}`}});const d=await r.json().catch(()=>({}));if(!r.ok){setMsg(d.detail||'Checkout indisponível');return}location.href=d.url}catch(e:any){setMsg(`Não foi possível acessar o backend de cobrança: ${e?.message||e}`)}}
 async function portal(){try{const r=await fetch(`${API}/api/v1/billing/portal`,{method:'POST',headers:{Authorization:`Bearer ${token()}`}});const d=await r.json().catch(()=>({}));if(!r.ok){setMsg(d.detail||'Portal indisponível');return}location.href=d.url}catch(e:any){setMsg(`Não foi possível acessar o backend de cobrança: ${e?.message||e}`)}}
 return <><div className="page-header"><div><span className="eyebrow">MONETIZAÇÃO</span><h1 className="page-title">Plano e assinatura</h1><p className="muted">Assinatura, limites e consumo do workspace.</p></div>{billing?.portal_ready&&<button className="btn" onClick={portal}>Gerenciar cobrança</button>}</div>{msg&&<div className="alert">{msg}</div>}{billing&&!billing.configured&&<div className="alert">Stripe ainda não está configurado no servidor. Preencha STRIPE_SECRET_KEY e os STRIPE_PRICE_*.</div>}{me&&<section className="card current-plan-card"><div className="current-plan-label">PLANO ATUAL</div><h2>{me.company.name}</h2><p>Plano atual: <b>{me.subscription.plan}</b> · {me.subscription.status}</p>{usage&&<p className="mini">Uso no mês: {usage.campaigns_created}/{usage.limits.campaigns_month||'—'} campanhas · {usage.publications_created}/{usage.limits.publications_month||'—'} publicações · {usage.ai_video_generations||0}/{usage.limits.ai_video_month??'—'} vídeos IA</p>}</section>}<div className="cards-grid">{plans.map(p=><section className={`card plan-card ${p.code===me?.subscription?.plan?'selected-plan':''}`} key={p.code}><span className="badge">{p.code}</span><h2>{p.name}</h2><h3>{`R$ ${(p.monthly_price_cents/100).toFixed(2).replace('.',',')}/mês`}</h3><p className="muted">{p.limits.users} usuários · {p.limits.campaigns_month} campanhas/mês · {p.limits.publications_month} publicações/mês · {p.limits.ai_video_month} vídeos IA/mês</p><button className="btn primary" disabled={p.code===me?.subscription?.plan&&me?.subscription?.status==='active'} onClick={()=>checkout(p.code)}>{p.code===me?.subscription?.plan&&me?.subscription?.status==='active'?'Plano ativo':`Escolher ${p.name}`}</button></section>)}</div></>
}
