"use client";
import {useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
type Conn={platform:string;configured:boolean;connected:boolean;account_name:string;expires_at?:string};
export default function Page(){const [key,setKey]=useState(""),[social,setSocial]=useState<Conn[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[meli,setMeli]=useState<any>(null);
 async function api(path:string,method="GET",socialApi=false){if(!key){setMessage("Informe a chave administrativa.");return null}setBusy(true);try{const r=await fetch(`${API}${socialApi?'/api/v1/social':'/api/integrations/mercadolivre'}/${path}`,{method,headers:{"X-Admin-Key":key},cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.detail||JSON.stringify(d));return d}catch(e){setMessage(String(e));return null}finally{setBusy(false)}}
 async function load(){const [m,s]=await Promise.all([api("status"),api("connections","GET",true)]);if(m)setMeli(m);if(s)setSocial(s)}
 async function connectMeli(){const d=await api("authorize","POST");if(d?.authorization_url)location.assign(d.authorization_url)}
 async function connectTikTok(){const d=await api("tiktok/authorize","POST",true);if(d?.authorization_url)location.assign(d.authorization_url)}
 async function disconnect(p:string){await api(`connections/${encodeURIComponent(p)}`,"DELETE",true);await load()}
 return <><div className="page-header"><div><span className="eyebrow">CONTAS E CANAIS</span><h1 className="page-title">Integrações</h1><p className="muted">Conecte marketplaces e redes sociais por autorização oficial. Tokens ficam no backend criptografados.</p></div></div><section className="card"><div className="field admin-field"><label>Chave administrativa</label><input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="ADMIN_SETUP_KEY"/></div><button className="btn primary" style={{marginTop:12}} disabled={!key||busy} onClick={load}>Consultar conexões</button>{message&&<div className="alert">{message}</div>}</section>
 <h2 style={{marginTop:28}}>Marketplaces</h2><div className="grid integration-grid"><div className="card"><h3>Mercado Livre</h3><span className={meli?.connected?"badge":"badge dim"}>{meli?.connected?"Conectado":"Não conectado"}</span><p className="muted">Catálogo próprio e OAuth do Mercado Livre.</p><button className="btn primary" onClick={connectMeli}>Conectar Mercado Livre</button></div><div className="card"><h3>SHEIN</h3><span className="badge dim">Pendente</span><p className="muted">Provider reservado para integração oficial do programa.</p></div></div>
 <h2 style={{marginTop:28}}>Redes sociais</h2><div className="grid integration-grid">{(["TikTok","Instagram","YouTube Shorts","Pinterest"] as string[]).map(p=>{const c=social.find(x=>x.platform===p);return <div className="card" key={p}><div className="variant-head"><h3>{p}</h3><span className={c?.connected?"badge":"badge dim"}>{c?.connected?"Conectado":c?.configured?"Pronto para conectar":"Configuração pendente"}</span></div><p className="muted">{c?.connected?`Conta autorizada${c.account_name?`: ${c.account_name}`:""}.`:"Configure as credenciais do aplicativo no .env e autorize a conta."}</p>{p==="TikTok"&&!c?.connected&&<button className="btn primary" disabled={!c?.configured} onClick={connectTikTok}>Conectar TikTok</button>}{p!=="TikTok"&&!c?.connected&&<button className="btn ghost" disabled>OAuth preparado para próxima ativação</button>}{c?.connected&&<button className="btn ghost" onClick={()=>disconnect(p)}>Desconectar</button>}</div>})}</div>
 <div className="alert" style={{marginTop:20}}>TikTok está implementado com OAuth e Content Posting API. Em clientes não auditados pelo TikTok, publicações de teste podem ficar restritas a privado. Instagram, YouTube e Pinterest já possuem o provider/estado de conexão no domínio, mas a chamada real permanece bloqueada até configurarmos e validarmos as credenciais/permissões de cada plataforma.</div></>}
