"use client";
import {useEffect,useState} from "react";
import {apiFetch} from "../../../lib/api";
type Conn={platform:string;configured:boolean;connected:boolean;account_name:string;expires_at?:string};
export default function Page(){const [social,setSocial]=useState<Conn[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[meli,setMeli]=useState<any>(null);
 async function api(path:string,method="GET",socialApi=false){setBusy(true);try{const r=await apiFetch(`${socialApi?'/api/v1/social':'/api/integrations/mercadolivre'}/${path}`,{method});const d=await r.json();if(!r.ok)throw Error(d.detail||JSON.stringify(d));return d}catch(e){setMessage(String(e));return null}finally{setBusy(false)}}
 async function load(){const [m,s]=await Promise.all([api("status"),api("connections","GET",true)]);if(m)setMeli(m);if(s)setSocial(s)}
 useEffect(()=>{load()},[]);
 async function connectMeli(){const d=await api("authorize","POST");if(d?.authorization_url)location.assign(d.authorization_url)}
 async function connectTikTok(){const d=await api("tiktok/authorize","POST",true);if(d?.authorization_url)location.assign(d.authorization_url)}
 async function disconnect(p:string){await api(`connections/${encodeURIComponent(p)}`,"DELETE",true);await load()}
 return <><div className="page-header"><div><span className="eyebrow">CONTAS E CANAIS</span><h1 className="page-title">Integrações</h1><p className="muted">As conexões pertencem à sua empresa. Tokens ficam criptografados no backend.</p></div><button className="btn ghost" disabled={busy} onClick={load}>Atualizar</button></div>{message&&<div className="alert">{message}</div>}
 <h2>Marketplaces</h2><div className="grid integration-grid"><div className="card"><h3>Mercado Livre</h3><span className={meli?.connected?"badge":"badge dim"}>{meli?.connected?"Conectado":"Não conectado"}</span><p className="muted">OAuth isolado para este workspace.</p><button className="btn primary" disabled={busy} onClick={connectMeli}>Conectar Mercado Livre</button></div><div className="card"><h3>SHEIN</h3><span className="badge dim">Pendente</span><p className="muted">Provider reservado para integração oficial.</p></div></div>
 <h2 style={{marginTop:28}}>Redes sociais</h2><div className="grid integration-grid">{(["TikTok","Instagram","YouTube Shorts","Pinterest"] as string[]).map(p=>{const c=social.find(x=>x.platform===p);return <div className="card" key={p}><div className="variant-head"><h3>{p}</h3><span className={c?.connected?"badge":"badge dim"}>{c?.connected?"Conectado":c?.configured?"Pronto para conectar":"Configuração pendente"}</span></div><p className="muted">{c?.connected?`Conta autorizada${c.account_name?`: ${c.account_name}`:""}.`:"Autorize a conta da empresa por OAuth."}</p>{p==="TikTok"&&!c?.connected&&<button className="btn primary" disabled={!c?.configured||busy} onClick={connectTikTok}>Conectar TikTok</button>}{p!=="TikTok"&&!c?.connected&&<button className="btn ghost" disabled>Próxima ativação</button>}{c?.connected&&<button className="btn ghost" onClick={()=>disconnect(p)}>Desconectar</button>}</div>})}</div></>}
