"use client";
import {useEffect,useState} from "react";
import {API,authToken} from "../../../lib/api";

type Plan={code:string;name:string;monthly_price_cents:number;currency:string;active:boolean;stripe_price_id:string;stripe_product_id:string;limits:any};
export default function Precos(){
 const[plans,setPlans]=useState<Plan[]>([]);const[values,setValues]=useState<Record<string,string>>({});const[msg,setMsg]=useState("");const[busy,setBusy]=useState("");
 async function load(){const r=await fetch(`${API}/api/v1/billing/admin/plans`,{headers:{Authorization:`Bearer ${authToken()}`}});const d=await r.json().catch(()=>({}));if(!r.ok){setMsg(d.detail||"Acesso restrito à administração da plataforma");return}setPlans(d);setValues(Object.fromEntries(d.map((p:Plan)=>[p.code,(p.monthly_price_cents/100).toFixed(2).replace('.',',')])))}
 useEffect(()=>{load().catch((e)=>setMsg(String(e)))},[]);
 async function save(p:Plan){const cents=Math.round(Number((values[p.code]||'0').replace('.','').replace(',','.'))*100);if(!Number.isFinite(cents)||cents<100){setMsg('Informe um preço mensal válido.');return}if(!confirm(`Alterar ${p.name} para R$ ${(cents/100).toFixed(2).replace('.',',')}/mês? O sistema criará um novo Price mensal no Stripe e usará esse preço para novas assinaturas.`))return;setBusy(p.code);setMsg('');try{const r=await fetch(`${API}/api/v1/billing/admin/plans/${p.code}`,{method:'PUT',headers:{Authorization:`Bearer ${authToken()}`,'Content-Type':'application/json'},body:JSON.stringify({monthly_price_cents:cents,create_stripe_price:true})});const d=await r.json().catch(()=>({}));if(!r.ok){setMsg(d.detail||'Não foi possível atualizar o preço');return}setMsg(`${p.name} atualizado. Novas assinaturas usarão o novo preço Stripe ${d.stripe_price_id}. Assinaturas existentes permanecem no preço contratado.`);await load()}finally{setBusy('')}}
 return <><div className="page-header"><div><span className="eyebrow">ADMINISTRAÇÃO COMERCIAL</span><h1 className="page-title">Preços dos planos</h1><p className="muted">Gerencie o catálogo comercial sem alterar código ou variáveis do deploy.</p></div></div>{msg&&<div className="alert">{msg}</div>}<div className="alert">Ao salvar, é criado um novo <b>Price</b> mensal no Stripe. Novas compras passam a usá-lo automaticamente; assinaturas existentes não são reajustadas silenciosamente.</div><div className="cards-grid">{plans.map(p=><section className="card plan-card" key={p.code}><span className="badge">{p.code}</span><h2>{p.name}</h2><label className="field"><span>Preço mensal (R$)</span><input value={values[p.code]||''} onChange={e=>setValues(v=>({...v,[p.code]:e.target.value}))}/></label><p className="mini">Price ativo: {p.stripe_price_id||'usa variável STRIPE_PRICE_'+p.code}</p><p className="muted">{p.limits.users} usuários · {p.limits.campaigns_month} campanhas · {p.limits.publications_month} publicações · {p.limits.ai_video_month} vídeos IA/mês</p><button className="btn primary" disabled={!!busy} onClick={()=>save(p)}>{busy===p.code?'Atualizando Stripe...':'Salvar novo preço'}</button></section>)}</div></>
}
