"use client";
import {apiFetch} from "../../../lib/api";
import {useEffect,useState} from "react";
import {Search,RefreshCw,ExternalLink,CheckCircle2,AlertCircle,Package,Link2,FileText,Sparkles,ChevronDown,Save} from "lucide-react";
type Product={id:number;external_id:string;title:string;marketplace:string;price:number;image_url:string;permalink:string;affiliate_url:string;affiliate_label:string;commission_rate:number;affiliate_ready:boolean;score:number|null;verified_discount_pct:number|null;history_count:number};
type Analysis={input_url:string;resolved_url:string;marketplace:string;external_id:string|null;title:string|null;image_url:string|null;price:number|null;affiliate_url:string|null;affiliate_detected:boolean;data_source:string;warnings:string[]};
const brl=(n:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(n||0);
export default function Products(){
 const [products,setProducts]=useState<Product[]>([]),[total,setTotal]=useState(0),[q,setQ]=useState(""),[filter,setFilter]=useState(""),[page,setPage]=useState(0),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [link,setLink]=useState(""),[analysis,setAnalysis]=useState<Analysis|null>(null),[analyzing,setAnalyzing]=useState(false),[saving,setSaving]=useState(false);
 const [title,setTitle]=useState(""),[price,setPrice]=useState(""),[commission,setCommission]=useState(""),[label,setLabel]=useState("");
 const [advanced,setAdvanced]=useState(false),[affiliateRows,setAffiliateRows]=useState(""),[batchBusy,setBatchBusy]=useState(false);
 async function load(){try{const r=await apiFetch(`/api/v1/products?limit=30&offset=${page*30}&q=${encodeURIComponent(q)}&marketplace=${encodeURIComponent(filter)}`,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();setProducts(d.items);setTotal(d.total)}catch(e){setError(String(e))}}
 useEffect(()=>{load()},[page,filter]);
 async function analyze(){setError("");setMessage("");setAnalysis(null);if(!link.trim()){setError("Cole um link do Mercado Livre ou meli.la.");return}setAnalyzing(true);try{const r=await apiFetch(`/api/v1/affiliates/mercadolivre/analyze`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:link.trim()})});const d=await r.json();if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);setAnalysis(d);setTitle(d.title||"");setPrice(d.price?String(d.price):"")}catch(e){setError(String(e))}finally{setAnalyzing(false)}}
 async function save(){if(!analysis)return;if(title.trim().length<3){setError("Confirme o título do produto.");return}setSaving(true);setError("");try{const rate=commission.trim()?Number(commission.replace(",",".")):null;const val=price.trim()?Number(price.replace(",",".")):null;if(rate!==null&&(rate<0||rate>100))throw new Error("Comissão deve ficar entre 0 e 100%.");const r=await apiFetch(`/api/v1/affiliates/mercadolivre/quick-save`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({analyzed_url:analysis.input_url,resolved_url:analysis.resolved_url,affiliate_url:analysis.affiliate_url,title:title.trim(),external_id:analysis.external_id,image_url:analysis.image_url,price:val,commission_rate:rate,label})});const d=await r.json();if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);setMessage(d.affiliate_ready?"Produto salvo e pronto para campanha.":"Produto salvo. O vínculo remunerado/comissão ainda precisa ser confirmado.");setLink("");setAnalysis(null);setTitle("");setPrice("");setCommission("");setLabel("");await load()}catch(e){setError(String(e))}finally{setSaving(false)}}
 async function importBatch(){setError("");const lines=affiliateRows.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!lines.length)return;const items:any[]=[];for(let i=0;i<lines.length;i++){const p=lines[i].split("|").map(x=>x.trim());if(p.length<3){setError(`Linha ${i+1}: formato inválido.`);return}const num=(x?:string)=>!x?null:Number(x.replace(",","."));items.push({original_url:p[0],affiliate_url:p[1],title:p[2],price:num(p[3]),commission_rate:num(p[4]),label:p[5]||"",external_id:p[6]||null})}setBatchBusy(true);try{const r=await apiFetch(`/api/v1/affiliates/mercadolivre/batch`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items})});const d=await r.json();if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);setMessage(`${d.created} novos, ${d.updated} atualizados, ${d.errors} falhas.`);if(!d.errors)setAffiliateRows("");await load()}catch(e){setError(String(e))}finally{setBatchBusy(false)}}
 return <>
 <div className="page-header"><div><span className="eyebrow">CATÁLOGO INTELIGENTE</span><h1 className="page-title">Adicionar produto</h1><p className="muted subheading">Cole um link. O Affiliate Intelligence tenta preencher o que estiver disponível automaticamente.</p></div><span className="pill"><Package size={13}/> {total} produtos</span></div>
 <section className="card smart-import"><div className="smart-head"><div className="smart-icon"><Sparkles size={24}/></div><div><h2 className="section-title" style={{marginBottom:5}}>Assistente de produto</h2><p className="muted" style={{margin:0}}>Aceita link do produto ou link remunerado <b>meli.la</b>. Sem campos separados por <b>|</b>.</p></div></div>
 <div className="smart-line"><input className="input big-input" value={link} onChange={e=>setLink(e.target.value)} onKeyDown={e=>e.key==="Enter"&&analyze()} placeholder="Cole aqui o link do produto ou https://meli.la/..."/><button className="btn primary" disabled={analyzing} onClick={analyze}>{analyzing?<><RefreshCw size={16}/> Analisando...</>:<><Sparkles size={16}/> Analisar produto</>}</button></div>
 {analysis&&<div className="analysis-card"><div className="analysis-product">{analysis.image_url?<img className="preview-img" src={analysis.image_url} alt=""/>:<div className="preview-img placeholder"><Package/></div>}<div><span className="badge">{analysis.marketplace}</span><h3>{title||"Título precisa ser confirmado"}</h3><div className="mini">{analysis.external_id||"ID MLB não exposto no link"}</div></div></div><div className="verify-grid"><label className="field"><span>Título {analysis.title?<em>automático</em>:<em>confirmar</em>}</span><input value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="field"><span>Preço {analysis.price?<em>detectado</em>:<em>opcional</em>}</span><input value={price} onChange={e=>setPrice(e.target.value)} placeholder="Ex.: 129,90"/></label><label className="field"><span>Comissão % <em>confirmar no programa</em></span><input value={commission} onChange={e=>setCommission(e.target.value)} placeholder="Ex.: 12"/></label><label className="field"><span>Etiqueta <em>opcional</em></span><input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Instagram, TikTok..."/></label></div><div className="status-strip"><span className={analysis.affiliate_detected?"status-ok":"status-warn"}>{analysis.affiliate_detected?"✓ Link remunerado detectado":"! Link remunerado ainda não detectado"}</span><span>Fonte: {analysis.data_source==="public_page_metadata"?"metadados públicos":"resolução do link"}</span></div>{analysis.warnings.length>0&&<div className="mini warning-text">{analysis.warnings.join(" • ")}</div>}<div className="toolbar" style={{justifyContent:"space-between",margin:"16px 0 0"}}><button className="btn primary" disabled={saving} onClick={save}><Save size={16}/> {saving?"Salvando...":"Salvar produto"}</button></div></div>}
 <div className="helper-row"><span className="mini">Se você colar apenas o produto, salvamos o que for verificável. O sistema nunca inventa comissão.</span><a className="btn ghost" href="https://www.mercadolivre.com.br/afiliados" target="_blank" rel="noopener noreferrer"><ExternalLink size={15}/> Central de afiliados</a></div></section>
 {error&&<div className="alert error"><AlertCircle size={16}/> {error}</div>}{message&&<div className="alert"><CheckCircle2 size={16}/> {message}</div>}
 <section className="card" style={{marginTop:20}}><button className="advanced-toggle" onClick={()=>setAdvanced(!advanced)}><span><b>Importação avançada em lote</b><small>Para operadores e migrações; até 100 produtos.</small></span><ChevronDown size={18} style={{transform:advanced?"rotate(180deg)":"none"}}/></button>{advanced&&<div style={{marginTop:18}}><div className="field"><label>URL original | Link afiliado | Título | Preço | Comissão | Etiqueta | ID MLB</label><textarea rows={5} value={affiliateRows} onChange={e=>setAffiliateRows(e.target.value)} placeholder="Uma linha por produto"/></div><div className="toolbar" style={{justifyContent:"flex-end",margin:"14px 0 0"}}><button className="btn primary" disabled={batchBusy||!affiliateRows.trim()} onClick={importBatch}>{batchBusy?"Importando...":"Importar lote"}</button></div></div>}</section>
 <section className="card" style={{marginTop:20}}><div className="page-header" style={{marginBottom:15}}><div><h2 className="section-title" style={{marginBottom:4}}>Catálogo monitorado</h2><span className="mini">Produtos persistidos no PostgreSQL</span></div><button className="btn ghost" onClick={load}><RefreshCw size={16}/></button></div><div className="toolbar"><label className="field"><span>Pesquisar</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nome do produto"/></label><label className="field"><span>Marketplace</span><select value={filter} onChange={e=>{setFilter(e.target.value);setPage(0)}}><option value="">Todos</option><option>Mercado Livre</option><option>SHEIN</option></select></label><button className="btn" onClick={()=>{setPage(0);load()}}><Search size={15}/> Buscar</button></div><div className="table-wrap"><table className="table"><thead><tr><th>Produto</th><th>Preço</th><th>Histórico</th><th>Afiliado</th><th>Score</th><th>Ações</th></tr></thead><tbody>{products.map(x=><tr key={x.id}><td><div className="product-cell">{x.image_url?<img className="thumb" src={x.image_url} alt=""/>:<div className="thumb placeholder"><Package/></div>}<div><strong>{x.title}</strong><div className="mini">{x.marketplace} · {x.external_id}</div></div></div></td><td><strong>{brl(x.price)}</strong></td><td><span className="mini">{x.history_count} coletas</span></td><td><span className={x.affiliate_ready?"badge":"badge dim"}>{x.affiliate_ready?"Pronto":"Pendente"}</span></td><td>{x.score??"—"}</td><td><div className="row-actions">{x.permalink&&<a className="btn ghost" href={x.permalink} target="_blank" rel="noopener noreferrer"><ExternalLink size={16}/></a>}<a className="btn ghost" href={`/conteudos?product=${x.id}`}><FileText size={16}/></a></div></td></tr>)}</tbody></table>{!products.length&&<div className="empty"><Package size={32}/><strong>Nenhum produto</strong>Cole um link acima para começar.</div>}</div><div className="toolbar" style={{justifyContent:"flex-end",margin:"15px 0 0"}}><span className="mini">{total} registros</span><button className="btn ghost" disabled={!page} onClick={()=>setPage(p=>p-1)}>Anterior</button><button className="btn ghost" disabled={(page+1)*30>=total} onClick={()=>setPage(p=>p+1)}>Próxima</button></div></section>
 </>;
}